/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Satellit_new.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Decke001: THREE.Mesh
    Grundriss002: THREE.Mesh
    Boden001: THREE.Mesh
    Fenster001: THREE.Mesh
    Traversen: THREE.Mesh
    Tür2001: THREE.Mesh
    Tür1001: THREE.Mesh
  }
  materials: {
    ['Material.005']: THREE.MeshStandardMaterial
    ['Wall Paint (White Wall Paint)']: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Satellit_new.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Decke001.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Grundriss002.geometry} material={materials['Wall Paint (White Wall Paint)']} />
      <mesh geometry={nodes.Boden001.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Fenster001.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Traversen.geometry} material={materials['Material.004']} position={[-3.051, 3.453, -1.501]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Tür2001.geometry} material={materials['Material.006']} position={[6.33, 1, 0.12]} />
      <mesh geometry={nodes.Tür1001.geometry} material={materials['Material.006']} position={[-6.33, 1, 2.372]} />
    </group>
  )
}

useGLTF.preload('/Satellit_new.glb')
