/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Satellit_new-optimized.glb --types --shadows --output src/components/Satellit.tsx 
*/

import * as THREE from 'three'
import { RectAreaLightUniformsLib } from 'three/examples/jsm/lights/RectAreaLightUniformsLib.js'
import React, { useMemo, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { useEditorStore } from '../store/editorStore'
import { SATELLIT_MODEL_URL } from '../lib/modelUrls'

// Required once for RectAreaLight to work with MeshStandardMaterial
RectAreaLightUniformsLib.init()

type GLTFResult = GLTF & {
  nodes: {
    Decke001: THREE.Mesh
    Grundriss002: THREE.Mesh
    Boden001: THREE.Mesh
    Fenster001: THREE.Mesh
    Traversen: THREE.Mesh
    Tür2001: THREE.Mesh
    Tür1001: THREE.Mesh
    Fensterbank: THREE.Mesh
  }
  materials: {
    ['Material.005']: THREE.MeshStandardMaterial
    ['Wall Paint (White Wall Paint)']: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Black marble.001']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

type SatellitProps = React.JSX.IntrinsicElements['group'] & {
  viewMode?: 'orthographic' | 'perspective' | 'firstPerson';
  /** RND-04: false in the "low" render preset. */
  rectAreaLights?: boolean;
}

export function Satellit({ viewMode = 'firstPerson', rectAreaLights = true, ...props }: SatellitProps) {
  const { nodes, materials } = useGLTF(SATELLIT_MODEL_URL) as unknown as GLTFResult
  const showTraverses = useEditorStore((state) => state.showTraverses);

  // Ensure wall material is visible from both sides (inside the room in first-person)
  useEffect(() => {
    materials['Wall Paint (White Wall Paint)'].side = THREE.DoubleSide;
  }, [materials]);

  // Compute ceiling bounding box to size and position the area light
  const ceilingLight = useMemo(() => {
    const box = new THREE.Box3().setFromObject(
      new THREE.Mesh(nodes.Decke001.geometry)
    )
    const size = new THREE.Vector3()
    const center = new THREE.Vector3()
    box.getSize(size)
    box.getCenter(center)
    return { width: size.x, height: size.z, posX: center.x, posY: box.min.y, posZ: center.z }
  }, [nodes.Decke001.geometry])

  return (
    <group {...props} dispose={null}>
      {rectAreaLights && (
        <>
          {/* Ceiling area light – positioned just below Decke001, facing downward */}
          <rectAreaLight
            width={ceilingLight.width}
            height={ceilingLight.height}
            color="#fff5e0"
            intensity={3.5}
            position={[ceilingLight.posX, ceilingLight.posY - 0.01, ceilingLight.posZ]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          {/* Upward-facing bounce light – simulates light scattering back off floor/walls */}
          <rectAreaLight
            width={ceilingLight.width}
            height={ceilingLight.height}
            color="#fff5e0"
            intensity={1.2}
            position={[ceilingLight.posX, ceilingLight.posY - 0.01, ceilingLight.posZ]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </>
      )}
      <mesh geometry={nodes.Decke001.geometry} material={materials['Material.005']} visible={viewMode === 'firstPerson'} />
      <mesh name="Wall" geometry={nodes.Grundriss002.geometry} material={materials['Wall Paint (White Wall Paint)']} />
      <mesh geometry={nodes.Boden001.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Fenster001.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Traversen.geometry} material={materials['Material.004']} position={[-3.051, 3.453, -1.501]} rotation={[0, Math.PI / 2, 0]} visible={showTraverses} />
      <mesh geometry={nodes.Tür2001.geometry} material={materials['Material.006']} position={[6.33, 1, 0.12]} />
      <mesh geometry={nodes.Tür1001.geometry} material={materials['Material.006']} position={[-6.33, 1, 2.372]} />
      <mesh geometry={nodes.Fensterbank.geometry} material={materials['Black marble.001']} />
    </group>
  )
}

// Module-level preload removed (LOAD-02): it forced every route, including
// the public home page, to download this model. The editor/viewer should
// call `useGLTF.preload(SATELLIT_MODEL_URL)` themselves
// once mounted instead.
